version: '3.7'

services:
  frontend:
    container_name: coinmarket-frontend
    hostname: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node_modules
    command: npx ng serve --host 0.0.0.0 --poll 2000
  api:
    container_name: coinmarket_api
    hostname: coinmarket_api
    image: coinmarket_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src
      - /usr/src/node_modules
      - ./.env:/usr/src/.env
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run dev
    depends_on:
      - mongo
  mongo:
    image: mongo
    hostname: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - $DB_PORT:$DB_PORT
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
      MONGO_INITDB_DATABASE: $DB_NAME
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:$DB_PORT/
    depends_on:
      - mongo
volumes:
  mongo_data:
