// <auto-generated />
using System;
using CoinMarketApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinMarketApi.Migrations
{
    [DbContext(typeof(CoinMarketContext))]
    partial class CoinMarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("CoinMarketApi.Models.Coin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CirculatingSupply")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CmcRank")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MarketCap")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaxSupply")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("NumMarketPairs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PercentChange24h")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PercentChange7d")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSupply")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Volume24h")
                        .HasColumnType("INTEGER");

                    b.Property<long>("price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Coins");
                });
#pragma warning restore 612, 618
        }
    }
}
